---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: brktm-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/cosmic-atomic
image-version: 44 

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: systemd
    system:
      enabled:
        - flatpak-firefox-policy.service
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - neovim
        - emacs
        - btop
        - pass
        - netcat
        - distrobox
        - zathura
        - zathura-pdf-poppler
        - picocom
        - tailscale
        - thunderbird
        
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
  - type: default-flatpaks
    configurations:
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.libreoffice.LibreOffice 
      - scope: user # Also add Flathub user repo, but no user packages
        install:
          - io.freetubeapp.FreeTube
          - org.gnucash.GnuCash
          - com.microsoft.Edge
          - org.localsend.localsend_app

  - type: fonts
    fonts:
      url-fonts:
        - name: PlexMono
          url: https://github.com/IBM/plex/releases/download/%40ibm%2Fplex-mono%402.5.0/ibm-plex-mono.zip
        - name: Iosevka
          url: https://github.com/be5invis/Iosevka/releases/download/v34.8.1/PkgTTF-Iosevka-34.8.1.zip 
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
